spring:
  application:
    name: fast-in
  profiles:
    active: dev
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  servlet:
    context-path: /api/v1

# Configuration commune pour les réservations
reservation:
  distance:
    max-km: 100
  price:
    base-rate: 10.0
    per-km-rate: 2.0

# Configuration de base des logs
logging:
  level:
    root: INFO
    com.fast_in: INFO
