spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fast_in_qa
    username: qa_user
    password: qa_password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  level:
    root: INFO
    com.fast_in: INFO

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
