spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fast_in_prod
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    root: WARN
    com.fast_in: INFO
